### ISSUE TITLE
Bitbucket repo is 404

### ISSUE THREAD

**Issue by Kirtai** [Wohlstand/libEDMIDI#9]
Just a note that the bitbucket repo linked in the readme is gone.

**Comment by Wohlstand** [comment]
Unexpected... I'll try to check out my local copy and I'll upload it as archived repo to preserve the thing.

**Comment by Wohlstand** [comment]
Updated, there is ALREADY preserved copy was at me with small updates over it.

So, by this commit https://github.com/Wohlstand/libEDMIDI/commit/26a0253cc046c106a7bbbaa6963930f3b3fd3ec4 I fixing this issue.
